enum WS_EVENTS {
  DELETED_MESSAGE = 'DELETED_MESSAGE',
  NEW_MESSAGE = 'NEW_MESSAGE',
  NOTIFICATION = 'NOTIFICATION',
  ADD_PARTICIPANT = 'ADD_PARTICIPANT',
  DELETE_PARTICIPANT = 'DELETE_PARTICIPANT',
  UPDATE_CHANNEL = 'UPDATE_CHANNEL',
  ADD_CHAT_CHANNEL = 'ADD_CHAT_CHANNEL',
  DELETE_CHAT_CHANNEL = 'DELETE_CHAT_CHANNEL',
}

export default WS_EVENTS;
